import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Nav from './Nav';

export default function Home() {

  return (
    <div>
      <Head>
        <title>Ashish Gupta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className="">
        <div className="mx-4 my-36 h-full">
          <p className="text-4xl font-medium">Hi, I am</p>
          <h1 className="text-8xl font-semibold name-font my-3">Ashish Gupta</h1>
          <p className="text-3xl">Web Developer</p>
        </div>

        <div className="mx-4 px-2">
          <h2>- About Me</h2>
          <p>
            Hi, I am a Frontend Developer. I have been working on the MERN stack 
            for about 6 months in this span I have developed multiple projects 
            which helped me to enhance my skills. Yes, having your strong base really 
            helps and hence I am open to adapting to whichever framework is required.
          </p>
        </div>
        {/* <button className={styles.btn}>Click Me</button> */}
      </main>

    </div>
  )
}
