import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Nav from './Nav';

export default function Home() {

  return (
    <div>
      <Head>
        <title>Ashish Gupta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className="">
        <div className="mx-4 my-36 h-full">
          <p className="text-4xl font-medium">Hi, I am</p>
          <h1 className="text-8xl font-semibold name-font my-3">Ashish Gupta</h1>
          <p className="text-3xl">Web Developer</p>
        </div>

        <div>
          <h2>About Me</h2>
        </div>
        {/* <button className={styles.btn}>Click Me</button> */}
      </main>

    </div>
  )
}
